services:
  mocap:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: isr/mct_acquisition
    tty: true
    stdin_open: true
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-localhost}
      PYTHONUNBUFFERED: 1
    volumes:
      - ${DATA_VOLUME:-/data}:/data
      - ${CAMERA_CONFIGS:-/camera_configs}:/configs
      - /etc/localtime:/etc/localtime:ro
      - ${DATAJOINT_EXTERNAL:-/mnt/datajoint_external}:/datajoint_external
    network_mode: host
    command: /Mocap/start_acquisition_gui.sh

  test:
    image: isr/mct_acquisition
    command: /Mocap/entrypoints/run_tests.sh
    volumes:
      - ${DATA_VOLUME:-/data}:/data
      - ${CAMERA_CONFIGS:-/camera_configs}:/configs
      - /etc/localtime:/etc/localtime:ro
      - ${DATAJOINT_EXTERNAL:-/mnt/datajoint_external}:/datajoint_external
      - ./tests:/Mocap/tests
      - ./tests/testdata:/Mocap/tests/testdata
    network_mode: host

  reset:
    image: isr/mct_acquisition
    command: /Mocap/entrypoints/run_reset.sh
    volumes:
      - ${CAMERA_CONFIGS:-/camera_configs}:/configs
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  annotate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.annotation
    image: isr/mct_annotation
    tty: true
    stdin_open: true
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-localhost}
      PYTHONUNBUFFERED: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATAJOINT_EXTERNAL:-/mnt/datajoint_external}:/datajoint_external
    network_mode: host
