version: '3'

services:
  mocap:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: peabody124/mocap
    tty: true
    stdin_open: true
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      PYTHONUNBUFFERED: 1
    volumes:
      - ${DATA_VOLUME}:/data
      - ${CAMERA_CONFIGS}:/configs
      - /etc/localtime:/etc/localtime:ro
      - ${DATAJOINT_EXTERNAL}:/datajoint_external
    network_mode: host
