version: '3'

services:
  mocap:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: peabody124/mocap
    tty: true
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      PYTHONUNBUFFERED: 1
    volumes:
      - ${DATA_VOLUME}:/data
      - ${CAMERA_CONFIG}:/configs
      - ${LOCAL_TIME}:/etc/localtime:ro
      - ${DATA_JOINT}:/datajoint_external
    network_mode: host
